added fun fact
DPI-WE/fun-facts pull request #150
Opened 2024-11-03 19:36 UTC by m-nt-s-no

2024-11-26 01:53 UTC, zer0mancer requested changes
I think you might've pulled before the new cohort was added. Could you check status and update so there are no conflicts?

2024-11-26 06:38 UTC, zer0mancer approved these changes

2024-12-12 23:03 UTC, grace1501 approved these changes
nice fact

2024-12-20 14:52 UTC, ricealonzo approved these changes
Looks great.

2024-12-20 16:14 UTC, merged